---
title: <span style="color:#c6316b"><strong> RStudio Pharma Updates
subtitle:  <span style="color:#c6316b"><strong>2021 Year in Review & Beyond</strong></span>
author: <span style="color:#black">twitter:@rinpharma github:philbowsher</span>
output:
  xaringan::moon_reader:
    css: "include/rstudio.css"
    nature:
      countIncrementalSlides: yes
      highlightLines: yes
      highlightStyle: github
      ratio: 16:9
resource_files:
  - include
  - images
---


```{r, include=FALSE}
rmarkdown::output_metadata$set(
  rsc_output_files = list.files("images", recursive = TRUE, full.names = TRUE)
)
```

class: subtitle-slide, white, middle, center

# For the last 7 years, I've helped Many pharmas adopt R. Usage around R in pharma, especially in clinical, has increased rapidly over the last 3 years, as seen at R in Pharma.
---



class: subtitle-slide, white, middle, center

# This talk will focus on the top 5 trends I saw in 2021 (as well as RStudio investments available to pharmas now) and make some predictions/thoughts for 2022 & beyond!
---





class: panel-narrow-slide, left
# RStudio is committed to creating high quality tools to help navigate these top challenges
- [Package Validation & Management](https://environments.rstudio.com/validation)
- [Scalable environment management via DevOps & MLOps](https://support.rstudio.com/hc/en-us/articles/360045105794-How-to-set-up-Git-backed-content-deployment-from-a-private-repository-in-RStudio-Connect)
- [Cloud](https://www.rstudio.com/blog/cloud-strategy/)
- [Shiny](https://learn.rinpharma.com/shiny4submissions.html)
- [User Focused Initiatives](https://www.rstudio.com/champion/)
- Small vs Large Pharmas
---

class: subtitle-slide, white, middle, center

# Package Validation & Management is still the top focus. This includes balancing the user and IT processes to access and recreate environments.
---


class: panel-narrow-slide, left
# Package Tools and Info
- [RStudio Package Validation Guidance](https://www.rstudio.com/solutions/pharma/)
- [RStudio Package Manager](https://docs.rstudio.com/rspm/admin/appendix/source-details/#curated-cran-source)
- [Surfacing Packages to users](https://solutions.rstudio.com/data-science-admin/packages/)
- [Migrating users from desktops to Server environments](https://www.rstudio.com/products/workbench/)
- [renv](https://rstudio.github.io/renv/articles/renv.html) & [Versioning renv.lock ](https://github.com/philbowsher/studious-octo-eureka/blob/master/renv.lock)
- [Adding internal packages](https://docs.rstudio.com/rspm/admin/building-packages/)
- [Internal Package Validation](https://rinpharma.com/publication/rinpharma_236/)
- [RISK-BASED APPROACH](https://www.pharmar.org/white-paper/)
- [Freeze repo](https://docs.rstudio.com/rspm/admin/repositories/#repo-versions) & [Example](https://colorado.rstudio.com/rspm/client/#/repos/10/overview)

---


class: subtitle-slide, white, middle, center

# Package management is only one part. What about system deps, OS versions...That broader environmental challenge is leading orgs to **containerization as a primitive**.
---



class: subtitle-slide, white, middle, center

# The ability to provide many different system configs leads to diverse packaging needs (RSPM). Allowing users to get access to those different containerized env at the same time for different projects/activities leads to k8s
---



class: subtitle-slide, white, middle, center

# The next top theme is interest or the move to scalable environment management via DevOps/MLOps. This includes tools for Production Deployments & Team Collaboration such as CI/CD & versioning.
---


class: panel-narrow-slide, left
# DevOps Tools and Info
- [Version Control via RStudio](https://www.pharmasug.org/proceedings/2021/AP/PharmaSUG-2021-AP-204.pdf)
- [Docker](https://environments.rstudio.com/docker)[ & Validated Images to spawn containers & Recipes](https://solutions.rstudio.com/sys-admin/launcher/kubernetes/)
- [renv](https://rstudio.github.io/renv/articles/renv.html)
- [Testing via testhat, covr & lintr](https://testthat.r-lib.org/)
- [RStudio Connect](https://www.rstudio.com/products/connect/) & [Cloud Devops tools](https://medium.com/rstudio-connect-digest/azure-devops-pipelines-for-deploying-content-to-rstudio-connect-e992f49103b6)
- [Git-backed deployments](https://docs.rstudio.com/connect/user/git-backed/) & [CI/CD](https://www.pharmasug.org/proceedings/2021/AD/PharmaSUG-2021-AD-205.pdf)
- [Vetiver](https://github.com/tidymodels/vetiver-r)
- [ETL](https://medium.com/rstudio-connect-digest/basic-builds-how-to-update-data-in-a-shiny-app-on-rstudio-connect-48593902b1e2) & [Pins](https://pins.rstudio.com/)

---

class: subtitle-slide, white, middle, center

# Next up is Cloud migrations...on one axis, scaling the ability of an org to provide flexible computational environemnts to increasingly heterogeneous needsets. The other axis taking advantage of the scale-out capability the cloud offers to bring unprecendented levels of computational resources into the hands of scientists on demand
---

class: panel-narrow-slide, left
# Cloud Info
- [Cloud Strategy](https://www.rstudio.com/blog/cloud-strategy/)
- [K8s](https://kubernetes.io/) via [aws](https://aws.amazon.com/eks/) & [MS](https://azure.microsoft.com/en-us/services/kubernetes-service/) & [Google](https://kubernetes.soleng.rstudioservices.com/#/overview?namespace=default)
- [Sagemaker](https://www.rstudio.com/sagemaker/)
- [VPC](https://aws.amazon.com/vpc/)
- [RStudio Launcher and Kubernetes](https://solutions.rstudio.com/sys-admin/launcher/kubernetes/)

---


class: subtitle-slide, white, middle, center

# 4th is Shiny...
---

class: panel-narrow-slide, left
# Shiny
- [Shiny for Submissions](https://learn.rinpharma.com/shiny4submissions.html)
- [Productionalizing Shiny Deployments](https://www.pharmasug.org/proceedings/2021/AD/PharmaSUG-2021-AD-205.pdf)
- [Future of Clinical tfls](https://realtimeclinical.shinyapps.io/rsum/)
- [Shiny via K8s](https://www.youtube.com/watch?v=H__CTvkI-8w)
- [Scaling Shiny](https://github.com/philbowsher/Advanced-Shiny-Deployments)

---


class: subtitle-slide, white, middle, center

# Last are user focused efforts...
---

class: panel-narrow-slide, left
# User enhancements
- [Upskilling](https://www.rstudio.com/academy/)
- [Internal Conferences](https://nhsrcommunity.com/) & [R in Pharma Champions](https://www.rstudio.com/champion/)
- [Clinical Tables via GT](https://gt.rstudio.com/)
- [Quarto: a scientific and technical publishing system](https://quarto.org/)
- [renv & git](https://www.pharmasug.org/proceedings/2021/AP/PharmaSUG-2021-AP-204.pdf)

---


class: subtitle-slide, white, middle, center

# RStudio recognizes that these are non-trivial challenges. We are committed to making our products adapt to these evolving needs, and also recognize that additional solutions are needed to provide the traceability and visibility into how all the pieces fit together in a compliant yet still scalable way
---

class: subtitle-slide, white, middle, center

# rstudio conference & rinpharma



